name: CI/CD - Build and Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: alan2442/projeto4
  IMAGE_TAG: v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Pega o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Push da imagem para Docker Hub
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG