name: CI/CD - Build, Push Docker Image & Update Manifests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: alan2442/projeto4
  IMAGE_TAG: v1

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Pega o código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # Login no Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build da imagem Docker
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # Push da imagem para Docker Hub
      - name: Push Docker image
        run: docker push $IMAGE_NAME:$IMAGE_TAG

      # Clonar o repositório de manifests
      - name: Checkout manifests repo
        uses: actions/checkout@v4
        with:
          repository: seu-usuario/hello-manifests
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: manifests

      # Atualizar a tag da imagem no deployment.yaml
      - name: Update image tag in manifests
        run: |
          cd manifests
          sed -i "s|image: .*|image: $IMAGE_NAME:$IMAGE_TAG|g" deployment.yaml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b update-image-$IMAGE_TAG
          git add deployment.yaml
          git commit -m "Atualiza imagem para $IMAGE_TAG"
          git push origin update-image-$IMAGE_TAG

      # Criar Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Atualiza imagem para $IMAGE_TAG"
          body: "Atualização automática via CI/CD"
          branch: update-image-$IMAGE_TAG
          base: main
